// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsqXvAl2ndnXshphGLJLYy27fTjdFt3uU',
    appId: '1:417628177777:web:c2bac290caba803caf62d0',
    messagingSenderId: '417628177777',
    projectId: 'login-sample-baacb',
    authDomain: 'login-sample-baacb.firebaseapp.com',
    storageBucket: 'login-sample-baacb.appspot.com',
    measurementId: 'G-MNVEZBC9PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-N_WYVk-k2bTKKIpkLAFaUUKLQBgTxQ',
    appId: '1:417628177777:android:6b605809897eb4ecaf62d0',
    messagingSenderId: '417628177777',
    projectId: 'login-sample-baacb',
    storageBucket: 'login-sample-baacb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATF15UDLJyd8pRgHPJLHY5YZmDu8Xc55U',
    appId: '1:417628177777:ios:2b6821a4746351cfaf62d0',
    messagingSenderId: '417628177777',
    projectId: 'login-sample-baacb',
    storageBucket: 'login-sample-baacb.appspot.com',
    androidClientId: '417628177777-et0f4d2nqbjvcibk8j52hng5fp8mlujq.apps.googleusercontent.com',
    iosClientId: '417628177777-qko14memkk0i9k7l5sdfa7t7sjb93ttg.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteAppSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATF15UDLJyd8pRgHPJLHY5YZmDu8Xc55U',
    appId: '1:417628177777:ios:2b6821a4746351cfaf62d0',
    messagingSenderId: '417628177777',
    projectId: 'login-sample-baacb',
    storageBucket: 'login-sample-baacb.appspot.com',
    androidClientId: '417628177777-et0f4d2nqbjvcibk8j52hng5fp8mlujq.apps.googleusercontent.com',
    iosClientId: '417628177777-qko14memkk0i9k7l5sdfa7t7sjb93ttg.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteAppSample',
  );
}
